@host1 = http://localhost:8080

###
GET {{host1}}/hello

###
GET {{host1}}/hello/up

###
GET {{host1}}/api/bonus

###
GET {{host1}}/api/bonus/JONES

###
POST {{host1}}/api/bonus
Content-Type: application/json

{
  "ename": "Zorro",
  "job": "MANAGER",
  "sal": 1234,
  "comm": 300
}

###
PUT {{host1}}/api/bonus/Zorro
Content-Type: application/json

{
  "ename": "Zorro",
  "job": "Salesman",
  "sal": 2344,
  "comm": 122
}

###
GET {{host1}}/api/bonus/Zorro

###
DELETE {{host1}}/api/bonus/Zorro

#

@jwt = Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjdlZWU0ZDc3LTE2N2ItNDM0NS1iNWRkLTgxMjhmNjQ4MmE2NSIsInN1YiI6ImRlbW8iLCJyb2xlcyI6IkFETUlOIiwiZXhwIjoxNzYzNjU3NTU2LCJhdWQiOiJodHRwczovL3d3d2NlcnQuYnBvcnR1Z2FsLm5ldC9hZGZzL29hdXRoMi90b2tlbiJ9.vjQfxFzHMIi6R21Rq8PvVLu1g0-W8MpARDAq4NiUIxk




###
POST {{host1}}/auth/login HTTP/1.1
content-type: application/json

{
  "uid": "demo",
  "pwd": "123",
  "aut": null
}

###
GET {{host1}}/auth/rnd HTTP/1.1
Authorization: {{jwt}}

###
GET {{host1}}/auth/valid?token={{jwt}} HTTP/1.1

###
GET {{host1}}/api/users

###
GET {{host1}}/api/users/count

###
POST {{host1}}/api/users
Content-Type: application/json

{
  "username": "demo",
  "passHash": "123",
  "role": "USER",
  "createdAt": "2001-02-01T00:00:00Z"
}
###
GET {{host1}}/api/users/7eee4d77-167b-4345-b5dd-8128f6482a65

###
PUT {{host1}}/api/users/7eee4d77-167b-4345-b5dd-8128f6482a65
Content-Type: application/json

{
  "username": "demo",
  "passHash": "sha:pmWkWSBCL51Bfkhn79xPuKBKHz//H6B+mY6G9/eieuM=",
  "role": "ADMIN",
  "createdAt": "2000-03-01T00:00:00Z"
}

###
GET {{host1}}/api/emp

###
GET {{host1}}/api/emp/count

###
GET {{host1}}/graphql/schema.graphql

###