@host1 = http://localhost:8080

###
GET {{host1}}/hello

###
GET {{host1}}/hello/up

###
GET {{host1}}/api/bonus

###
GET {{host1}}/api/bonus/JONES

###
POST {{host1}}/api/bonus
Content-Type: application/json

{
  "ename": "Zorro",
  "job": "MANAGER",
  "sal": 1234,
  "comm": 300
}

###
PUT {{host1}}/api/bonus/Zorro
Content-Type: application/json

{
  "ename": "Zorro",
  "job": "Salesman",
  "sal": 2344,
  "comm": 122
}

###
GET {{host1}}/api/bonus/Zorro

###
DELETE {{host1}}/api/bonus/Zorro

#

@jwt = Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwic3ViIjoiZGVtbyIsInJvbGVzIjoiVVNFUiIsImV4cCI6MTc0MjY5Njc4OCwiYXVkIjoiaHR0cHM6Ly93d3djZXJ0LmJwb3J0dWdhbC5uZXQvYWRmcy9vYXV0aDIvdG9rZW4ifQ.pcP2Y3SFcRIsbaQQbrdWcN3DOonHBn3GyGlBUqHnbNw


###
POST {{host1}}/auth/login HTTP/1.1
content-type: application/json

{
  "uid": "demo",
  "pwd": "123",
  "aut": null
}

###
GET {{host1}}/auth/rnd HTTP/1.1
Authorization: {{jwt}}

###
GET {{host1}}/auth/valid?token={{jwt}} HTTP/1.1
